/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'stock-analysis-stream': MotiaStream<{ id: string; symbol: string; status: string }>
  }

  interface Handlers {
    'StockAnalysisAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; traceId: string }>, { topic: 'process-stock-analysis'; data: { symbol: string } }>
    'ProcessReverseDcfAnalysis': EventHandler<{ symbol: string }, { topic: 'finish-reverse-dcf-analysis'; data: { symbol: string } }>
    'return-db': EventHandler<{ symbol: string }, never>
    'RateStock': EventHandler<{ symbol: string }, { topic: 'finish-stock-rating'; data: { symbol: string } }>
    'ProcessStockAnalysis': EventHandler<{ symbol: string }, { topic: 'finish-stock-qualitative-analysis'; data: { symbol: string } }>
    'ProcessGrowthJudgement': EventHandler<{ symbol: string }, { topic: 'finish-growth-judgement'; data: { symbol: string } }>
    'DCF': EventHandler<{ symbol: string }, { topic: 'finish-dcf'; data: { symbol: string } }>
  }
    
}