from __future__ import annotations

APP_ENV = "development"
APP_LOG_LEVEL = "INFO"
FRONTEND_URL = "http://localhost:3000"

FMP_BASE_URL = "https://financialmodelingprep.com"
FMP_TIMEOUT_SECONDS = 30

MAINTENANCE_SEED_TARGET_COUNT = 100
MAINTENANCE_SEED_MIN_MARKET_CAP = 10000000000

WORKFLOW_NODE_HEARTBEAT_INTERVAL_SECONDS = 15
WORKFLOW_STALE_PROGRESS_THRESHOLD_SECONDS = 120
WORKFLOW_STALL_MONITOR_INTERVAL_SECONDS = 30
WORKFLOW_STALL_SIGNAL_COOLDOWN_SECONDS = 300

GOOGLE_GENAI_USE_VERTEXAI = True
VERTEX_AI_LOCATION = "global"

DEEP_RESEARCH_AGENT = "deep-research-pro-preview-12-2025"
LLM_FLASH_LITE_MODEL = "gemini-3.1-flash-lite-preview"
STRUCTURED_OUTPUT_MODEL = LLM_FLASH_LITE_MODEL
DEEP_RESEARCH_DEV_MODEL = LLM_FLASH_LITE_MODEL
DEEP_RESEARCH_DEV_GROUNDING_ENABLED = True
DEEP_RESEARCH_USE_ENDPOINT_IN_PRODUCTION = True
DEEP_RESEARCH_POLL_INTERVAL_SECONDS = 10
DEEP_RESEARCH_MAX_WAIT_SECONDS = 1200
DEEP_RESEARCH_ENABLE_LIVE_CALLS = False
CHAT_ENABLE_LIVE_CALLS = True

SKIP_DEEP_RESEARCH_IN_TESTS = False

MEMORY_DEFAULT_USER_ID = "local-user"
MEMORY_RECALL_MAX_CANDIDATES = 40
MEMORY_PROMPT_TOPK = 8
MEMORY_SUMMARY_MAX_CHARS = 900
MEMORY_WRITE_CONFIDENCE_THRESHOLD = 0.8
MEMORY_JOB_MAX_RETRIES = 2
MEMORY_COMPRESSION_MIN_WRITES = 8
MEMORY_COMPRESSION_INJECTED_CHAR_LIMIT = 1000
MEMORY_COMPRESSION_MAX_SUMMARY_AGE_HOURS = 24
MEMORY_COMPRESSION_COOLDOWN_MINUTES = 10
TURN_STRUCTURED_OUTPUT_ENABLED = True
TURN_SCHEMA_RETRY_MAX = 3
TURN_SCHEMA_REPAIR_ENABLED = True
MEMORY_SUGGESTION_FALLBACK_MODE = "rule_based"
MEMORY_SUGGESTION_MAX_CANDIDATES = 6

